### ISSUE TITLE
`NullReferenceException` in `PlotlyJsInterop` `React` call when calling `Chart.Update`

### ISSUE THREAD

**Issue by hypdeb** [LayTec-AG/Plotly.Blazor#173]
Code belows throws `NullReferenceException` on call to `Update`.

```
<PlotlyChart @bind-Config="config" @bind-Layout="layout" @bind-Data="data" @ref="chart"/>

@code {
  [Parameter] public IReadOnlyCollection<Bar<T>> Bars { get; set; } = null!;

  public PlotlyChart chart = new();

  public Config config = new()
  {
      Responsive = true,
  };

  public Plotly.Blazor.Layout layout = new()
  {
      DragMode = DragModeEnum.Zoom,
      Margin = new Margin
      {
          R = 10,
          T = 25,
          B = 40,
          L = 60,
      },
      XAxis = new List<XAxis>
      {
          new()
          {
              AutoRange = AutoRangeEnum.True,
              Type = typeof(T) == typeof(double) ? TypeEnum.Linear : TypeEnum.Date,
          },
      },
      YAxis = new List<YAxis>
      {
          new()
          {
              AutoRange = Plotly.Blazor.LayoutLib.YAxisLib.AutoRangeEnum.True,
              Type = Plotly.Blazor.LayoutLib.YAxisLib.TypeEnum.Linear,
          },
      },
      Height = 800,
      Title = new Title(),
  };

  private List<ITrace> GetData()
  {
    // Omitted...
  }

  protected override async Task OnParametersSetAsync()
  {
      this.data = this.GetData();
      try
      {
          await this.chart.Update();
      }
      catch
      {
      }
      await this.InvokeAsync(this.StateHasChanged);
  }
}

```

Somehow if I catch the exception, I still get the chart displayed.

**Comment by sean-mcl** [comment]
Please update the chart in the AfterRender-Method.

```
protected override async Task OnAfterRenderAsync(bool firstRender)
{
  if (firstRender)
  {
     await  chart.Update();
  }
}
```

The chart has to be rendered before you can edit it.

Let me know if that fixes the problem.

**Comment by hypdeb** [comment]
So I now changed my code a bit and made it better I think, and I'm getting this instead:
```
Cannot access a disposed object.
Object name: 'DotNetObjectReference`1'.
```
at
```
   at Microsoft.JSInterop.DotNetObjectReference`1.ThrowIfDisposed()
   at Microsoft.JSInterop.DotNetObjectReference`1.get_Value()
   at Plotly.Blazor.PlotlyJsInterop.<React>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Plotly.Blazor.PlotlyChart.<React>d__49.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Plotly.Blazor.PlotlyChart.<Update>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Torchlight.Ui.Shared.BarChartComponent`1.<>c__DisplayClass5_0.<<OnInitializedAsync>b__1>d.MoveNext() in D:\torchlight\Torchlight\Torchlight.Ui\Shared\BarChartComponent.razor.cs:line 94
```
This is definitely called after the page and the chart has already been rendered once.

**Comment by hypdeb** [comment]
![image](https://user-images.githubusercontent.com/18333810/168381601-2efa7eee-4ab1-4719-b1b5-2c74bf898648.png)
Here is a further clue. How do I prevent this from being disposed ?

**Comment by sean-mcl** [comment]
You are not allowed to rerender the chart, otherwise the dom element with the given reference is lost.
Are you using StateHasChanged?

**Comment by hypdeb** [comment]
Okay this is solved. If someone facing the same issue reaches this post : using `@if` around the parent component was causing this reference to be disposed. I would consider it a bug, but probably more of the wider framework and not of this library in particular.

Otherwise, your solution above solved my issue in a way, because moving the `chart.Update` to somewhere after the rendering now doesn't get me the original `NullReferenceException`. Thus, thanks for your assistance !

**Comment by sean-mcl** [comment]
Thanks for enlightening. 🤝
