### ISSUE TITLE
4.2.0 and 4.3.0 Exception is thrown if plot is de-rendered while still lazy loading

### ISSUE THREAD

**Issue by OliverWingY** [LayTec-AG/Plotly.Blazor#428]
Using the following two components, clicking the button twice in quick succession will throw the following exception: ,"Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: No DOM element with id 'PlotlyChart-1695005480' exists on the page.
      Error: No DOM element with id 'PlotlyChart-1695005480' exists on the page."

This can also occur if you navigate away from the page while a plot is lazy loading, although I was able to work around that by intercepting the OnLocationChanging event from the NavigationManager and waiting for the chart to finish loading before navigating away.

This causes a lot of issues if you want to embed a plotly chart in an expandable components, like a tree or grid.

Home.razor
```
@page "/"

<button @onclick="TogglePlot">Toggle graph</button>

@if (_plotVisible)
{
    <Plot></Plot>
}

@code
{
    
    private bool _plotVisible = false;

    private void TogglePlot()
    {
        _plotVisible = !_plotVisible;
        StateHasChanged();
    }
}
```

Plot.razor:
```
@using Plotly.Blazor
@using Layout = Plotly.Blazor.Layout
@using Plotly.Blazor.Traces.ScatterLib
@using Plotly.Blazor.Traces
@using Line = Plotly.Blazor.Traces.ScatterLib.Line
@using System.Drawing


<div style="height: 50%; width: 50%;">
    <PlotlyChart @bind-Config="@_config" @bind-Layout="_layout" @bind-Data="_data" @ref="_chart"></PlotlyChart>
</div>

@code {
    protected Config _config = new Config();
    protected Layout _layout = new Layout();
    protected PlotlyChart _chart;

    private IList<ITrace> _data = new List<ITrace>();


    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await AddData();
            await _chart.React();
        }
        await base.OnAfterRenderAsync(firstRender);
    }

    public async Task AddData()
    {
        _data.Add(new Scatter()
            {
                Name = "Test",
                Mode = ModeFlag.Lines,
                Line = new Line() { Dash = "dash", Color = Color.Blue.ToString() },
                X = new List<object>() { 1.0, 2.0, 3.0 },
                Y = new List<object>() { 1.0, 2.0, 3.0 },
                ShowLegend = false
            });

    }
}
```

**Comment by sean-mcl** [comment]
Will check it out next week. :)

**Comment by sean-mcl** [comment]
Should be fixed by https://github.com/LayTec-AG/Plotly.Blazor/pull/432

**Comment by OliverWingY** [comment]
Looks like the bug still present in 5.0.0 and 5.1.1

**Comment by sean-mcl** [comment]
Plotly.Blazor has an own "AfterRender"-Event, have you tried this one?

**Comment by OliverWingY** [comment]
Yeah I wasn't able to fix the issue, I think it's something even lower level than that as I've been able to reproduce the bug with no calls to the plotly chart

```
@page "/"

@using Plotly.Blazor
@using Layout = Plotly.Blazor.Layout

<button @onclick="TogglePlot">Toggle graph</button>

@if (_plotVisible)
{
    <div style="height: 50%; width: 50%;">
        <PlotlyChart @bind-Config="@_config" @bind-Layout="_layout" @bind-Data="_data" @ref="_chart" ></PlotlyChart>
    </div>
}

@code
{
    protected Config _config = new Config();
    protected Layout _layout = new Layout();
    protected PlotlyChart _chart;
    private IList<ITrace> _data = new List<ITrace>();
    private bool _plotVisible = false;

    private void TogglePlot()
    {
        _plotVisible = !_plotVisible;
        StateHasChanged();
    }
}

```

**Comment by sean-mcl** [comment]
Let me try.

**Comment by sean-mcl** [comment]
Yeah, I can't reproduce it.

Are you still referencing the *.js files in the Layout.cshtml?

https://github.com/user-attachments/assets/a5ef2339-3108-45f3-910e-5732b4765f92

**Comment by OliverWingY** [comment]
Only happens on the first render before any plotly charts have been loaded into the page, and when there's no data in this case I have to be very quick.


https://github.com/user-attachments/assets/075013ac-fd25-40c5-af2d-21718b3dd852

**Comment by sean-mcl** [comment]
Okay, i still can't reproduce it on my machine. But maybe there is an edge condition in the OnPlotlyReady event and maybe needs a small delay before rendering the chart.

**Comment by sean-mcl** [comment]
@OliverWingY Can you try the pre version please [5.1.2-bugfix-lazy-loading.1](https://www.nuget.org/packages/Plotly.Blazor/5.1.2-bugfix-lazy-loading.1)

**Comment by OliverWingY** [comment]
Yeah I'm still getting the issue, looking at the error I think its that the div doesn't exist anymore as it has been derendered it. I'm currently looking to see if there's a fix on the blazor component side of things.

**Comment by OliverWingY** [comment]
Can no longer reproduce the issue in 5.1.2 :)

**Comment by Thoronion** [comment]
I get this error in 6.0.1. We can reproduce it 100 % of the time when we publish the app but not on the local machine. We have two plots in the same component and it is always the first plot that fails rendering. The second plot works as expected.

plotly-3.0.0.min.js:18 Uncaught Error: No DOM element with id 'PlotlyChart1159498267' exists on the page.
    at Object.itt [as getGraphDiv] (plotly-3.0.0.min.js:18:162645)
    at Object.Qft [as newPlot] (plotly-3.0.0.min.js:21:260623)
    at plotly-interop-6.0.0.js:57:23
    at plotly-interop-6.0.0.js:32:54
    at Array.forEach (<anonymous>)
    at script.onload (plotly-interop-6.0.0.js:32:34)
