### ISSUE TITLE
Could not find 'plotlyInterop.newPlot' ('plotlyInterop' was undefined).

### ISSUE THREAD

**Issue by DavidDXY** [LayTec-AG/Plotly.Blazor#98]
I used this library in the .net5 project. I added the library package according to the instructions in the markdown document, and the console reported an error during runtime:

      Unhandled exception rendering component: Could not find 'plotlyInterop.newPlot' ('plotlyInterop' was undefined).
Error: Could not find 'plotlyInterop.newPlot' ('plotlyInterop' was undefined).
    at https://localhost:5001/_framework/blazor.server.js:1:67713
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:5001/_framework/blazor.server.js:1:67673)
    at v (https://localhost:5001/_framework/blazor.server.js:1:69415)
    at https://localhost:5001/_framework/blazor.server.js:1:70361
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:1:70334)
    at https://localhost:5001/_framework/blazor.server.js:1:26441
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:26411)
      Microsoft.JSInterop.JSException: Could not find 'plotlyInterop.newPlot' ('plotlyInterop' was undefined).

**Comment by DavidDXY** [comment]
Sorry，I copied the script in the wrong place and it is not quoted
